---
- name: Get current global pull secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: pull-secret
    namespace: openshift-config
  register: r_global_pull_secret

- name: Decode current global pull secret
  ansible.builtin.set_fact:
    r_current_dockerconfig: "{{ r_global_pull_secret.resources[0].data['.dockerconfigjson'] | b64decode | from_json }}"

- name: Decode ACS pull secret
  ansible.builtin.set_fact:
    r_acs_dockerconfig: "{{ ocp5_rhacs_acs_pull_secret | b64decode | from_json }}"

- name: Merge ACS credentials into global pull secret (as quay.io/rhacs-eng only)
  ansible.builtin.set_fact:
    r_merged_dockerconfig: "{{ r_current_dockerconfig | combine({'auths': r_current_dockerconfig.auths | combine({'quay.io/rhacs-eng': r_acs_dockerconfig.auths['quay.io']})}) }}"

- name: Update global pull secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: pull-secret
        namespace: openshift-config
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ r_merged_dockerconfig | to_json | b64encode }}"
